### ISSUE TITLE
Error: connect ECONNREFUSED

### ISSUE THREAD

**Issue by waspeer** [getjackd/jackd#13]
Hi!

I'm getting this error while trying to connect:

```
(node:38072) UnhandledPromiseRejectionWarning: Error: connect ECONNREFUSED 127.0.0.1:11300
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16)
```

It's hard to tell where this issue is coming from and what I can do about it. This was the test code I was running:

```javascript
const Jackd = require("jackd");
const beanstalkd = new Jackd();

beanstalkd.connect();
```

**Comment by ruffrey** [comment]
Sounds like beanstalkd isn't running on your local machine...

**Comment by waspeer** [comment]
Aah ofcourse, I was assuming that this solution included beanstalkd, but obviously I don't understand the whole thing well enough yet 😅 My bad! Thanks!
