### ISSUE TITLE
Getting response for previous command

### ISSUE THREAD

**Issue by wilensky** [getjackd/jackd#29]
Hi @divmgl!

I've got into a situation when I receive response for a previous command and I would like to know whether I'm doing smth. wrong or in what cases this can happen❓ 

> ℹ️ I do not have concurrent usage of Jackd client, everything goes sequentially using `await` or `.then().then()...` chain.

So the case is that on worker init I'm doing `watch(tube)` the following way

```ts
client
  .watch(tube)
  .then(() => {
    logger.debug({ tube, type }, 'Beanstalkd connection watching tube');
    return client.ignore(JOBQUEUE_TUBES.Default);
  })
  .then(() => {
    logger.debug({ tube: JOBQUEUE_TUBES.Default, type }, 'Beanstalkd connection ignoring tube');
    return client;
 });
```

but on further `.reserve()` I'm getting `Unexpected response: WATCHING 2` which I suppose a response from previous `watch` command.

```
Error: Unexpected response: WATCHING 2
    at invalidResponse (/usr/app/node_modules/jackd/dist/index.js:379:19)
    at id.id (/usr/app/node_modules/jackd/dist/index.js:304:17)
    at JackdClient.flushExecutions (/usr/app/node_modules/jackd/dist/index.js:244:42)
    at JackdClient.processChunk (/usr/app/node_modules/jackd/dist/index.js:228:24)
    at Socket.<anonymous> (/usr/app/node_modules/jackd/dist/index.js:210:24)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
```

By reaching `reserve` we already have `watch` Promise resolved earlier on init otherwise we wouldn't get through.

Where I'm wrong and how one would reproduce this❓

> 🏃 Running `node:18.12.1-bullseye` in EKS

**Comment by divmgl** [comment]
Hi @wilensky! I realize it's been a very long time, but hopefully you still find this useful. 

I just made a couple of small scripts to test it and run it and had no issues reserving a job:

```js
// consumer.js
const Jackd = require('./dist')
const client = new Jackd()

const tube = 'my_tube'
const defaultTube = 'default'

client
  .connect()
  .then(() => {
    return client.watch(tube)
  })
  .then(() => {
    console.log({ tube }, 'Beanstalkd connection watching tube')
    return client.ignore(defaultTube)
  })
  .then(() => {
    console.log({ tube: defaultTube }, 'Beanstalkd connection ignoring tube')
    return client
  })
  .then(() => {
    return client.reserve()
  })
  .then(console.log) // Job get logged
```
```js
// producer.js
const Jackd = require('./dist')
const client = new Jackd()

const tube = 'my_tube'

client
  .connect()
  .then(() => {
    return client.use(tube)
  })
  .then(() => {
    return client.put("some random job!")
  })
```
```
jackd on  master [!?] via 🐳 desktop-linux is 📦 v2.1.2 via  v18.16.0
❯ node consumer.js
{ tube: 'my_tube' } Beanstalkd connection watching tube
{ tube: 'default' } Beanstalkd connection ignoring tube
{
  id: '1',
  payload: <Buffer 73 6f 6d 65 20 72 61 6e 64 6f 6d 20 6a 6f 62 21>
}
```

I'm sorry you're running into these issues! My suggestion would be to check your promise chains as it's likely you're not returning a promise somewhere. Additionally I'd recommend not using the `.then/catch/finally` API anymore and instead moving over to `async/await` which is significantly easier to manage.

If this does continue to happen please submit a reproduction and I'm happy to take a look!
