### ISSUE TITLE
reserveJob's NOT_FOUND is treated as unknown

### ISSUE THREAD

**Issue by tolgaulas** [getjackd/jackd#34]
reserveJob(jobId) may return NOT_FOUND. The current  common reserveHandler's `validation` does not include this case at
https://github.com/getjackd/jackd/blob/master/src/index.ts#L565 ; resulting an irregular error message. 

Would you please add `NOT_FOUND` into the potential error messages for validation?

**Comment by divmgl** [comment]
Hi @tolgaulas! Thanks for reporting this! This is a valid issue and needs to be addressed. Appreciate you using this package!
