### ISSUE TITLE
Is there a way to watch multiple tubes based on a regex string?

### ISSUE THREAD

**Issue by RyanSMurphyDMCo** [getjackd/jackd#9]
I have a regex string which will catch all the tubes I want to watch for my consumer. Is there a way I can do this using this library?

If not, is it something you would consider adding?

I would list all the tubes out and run regex against all of them and watch the matched ones but I can't seem to find a way to list all tubes, could you perhaps help with that?

Thanks

**Comment by divmgl** [comment]
Hello! Unfortunately, the beanstalkd protocol does not support this so we would not be able to implement this in `jackd`.

**Comment by divmgl** [comment]
Hi!

I realize this was almost two years ago (wow, time flies) but `jackd` now has support for `list-tubes`. You can pipe the response through a YAML parser to turn the buffer into an array. After that you can just apply a regex on top using a `filter` and viola! Hope this helps!
